Kenny/isoform
latch-verified/bulk-rnaseq pull request #7
Opened 2022-09-03 16:03 UTC by kennyworkman

Introduces:
    * splice aware mapping (STAR)
    * exon-exon junction extraction (regtools)
    * splice graph clustering (leafcutter)

Interactive report for interacting with splice graphs still tbd

2022-09-03 16:04 UTC, kennyworkman commented
would like to pull out trimgalore as upstream of both salmon and STAR so they can be run in parallel if scientist wants both counts and splice junctions

2022-09-12 15:09 UTC, ayushkamat requested changes

2022-09-12 15:09 UTC, ayushkamat commented on wf/__init__.py
> +        print(f"Handling failure in trmming {input.sample_name} gracefully.")
```suggestion
        print(f"Handling failure in trimming {input.sample_name} gracefully.")
```

2022-09-12 15:09 UTC, ayushkamat commented on wf/__init__.py
> +                    "aws",
would it be better to use s5cmd here

2022-09-12 15:09 UTC, ayushkamat commented on wf/__init__.py
>          if "." in unwanted:
this is hacky, use `path.exists()` and `path.is_file()` instead

2022-09-12 15:09 UTC, ayushkamat commented on wf/__init__.py
> +        repository: github.com/latchbio/rnaseq
why this change

2022-09-12 15:09 UTC, ayushkamat commented on wf/__init__.py
> +def noop() -> None:
doesnt seem like this is being used anywhere

2022-09-12 18:40 UTC, kennyworkman commented on wf/__init__.py
>          if "." in unwanted:
yeah this is artifact of the previous author...

2022-09-12 18:48 UTC, kennyworkman commented
will take the opportunity to close https://github.com/latchbio/lgenome/issues/3

2022-09-12 18:51 UTC, kennyworkman commented
as well as #9

2022-10-01 01:59 UTC, merged